sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gt4wIWPQAYiCFnXt9MIfQudfwb2fOFZsuwBsxcCcpbjlidIWyVtXCCAljHIIXctUaObFUsDrRmCq7RwpdvvTKJILlHyskXA9KzDWjuQzn+xe4hHFm7ua9Rq4fUcud3nA/RwQFHB9oO2c8bmyfB9ijEq/Pcvkhofar1+I+P30mjHoCwZcFhl1QBZEMiGZIkzdlkqaDBhLjX9hdAI+H7EAymyrkUp+yc0eoyZuBC7DtHccdHTF56zMjT62tVi9QgWgjPZGpGqmH1/M13pSJ/QxS8fQKVbkX53kr4v1TNtVKGAS8VQA7t9wZcVJtXpDDIr5VwhXEipa8mfu1lthpPtYskfXmz89BoYDuCZ0Eb0lXDFVpcfcKrO0CafiOTPr1bPogv6vvBi8GGAtMLsV5Gd2uVW8VDCmy2OsUU8Q2gzIPctOz2OHjfU+heR689kOccTkt/fJ2gR/+7cJBTsOqkiQ9BauVNtywml9UXi6CV5ZlOkZ4wypbdf4GzzjP/Gkyn8gEYZqe2dXzNH+jomhB4HrM/CTt2GXEMSttPn8z2o0VH5N7mALgibbtCn73jTjmzJnE5fV6pMqXURF1XTQrXRR4WZVBnx6O3zd+onmSCvxUAqk05NmKS3aeOTWGgvVQl4kvF8pT9xEhOJ2itDYryzJDd2WmrjlZuER4EAwTXag+Mk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Lavender-and-Old-Lace_1266
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy